import {createContext} from 'react';
import WeddingImg from '../img/servicesHeader/wedding.jpg';
import EventImg from '../img/servicesHeader/event.jpg';
import EntertainmentImg from '../img/servicesHeader/entertainment.jpg';
import PhotographyImg from '../img/servicesHeader/photography.jpg';
import MovieImg from '../img/servicesHeader/movie.jpg';
import DrinkImg from '../img/servicesHeader/drink.jpg';

export const services = {
    pageContain:[
        {id: "wedding",img: WeddingImg, title: "wesela", heading: "Naszą pasją jest zapewnienie Państwu profesjonalnej oprawy muzycznej wesela.", description: "Zapewniamy najwyższy poziom obsługi muzycznej każdego wesela, które z naszą obsługą będzie najlepszym wydarzeniem w Państwa życiu. Przygotujemy dla Państwa najlepszy repertuar muzyczny, stworzony z naszej pasji i Państwa oczekiwań, idealnie trafiony w gust muzyczny wszystkich zaproszonych gości. O niezapomnianą obsługę muzyczną dbają najlepsi w kraju DJ-e, wokaliści oraz profesjonalni muzycy, a subtelna konferansjerka perfekcyjnie zadba o wyjątkowy klimat Państwa wesela. Zapewniamy także na Państwa życzenie zachwycające atrakcje, które doskonale uchwycą najpiękniejsze momenty imprezy."},

        {id:"event",img: EventImg, title: "eventy", heading: "Organizacja i obsługa imprez firmowych", description: "Imprezy firmowe to doskonała chwila na integrację zespołu. Dlatego tak ważne jest zapewnienie korporacyjnym ventom najlepszej oprawy muzycznej. Przygotujemy dla Państwa pracowników najlepiej zorganizowaną i dopracowaną w najdrobniejszym szczególe oprawę muzyczną imprezy na terenie całej Polski. Dbamy o profesjonalną oprawę każdego eventu, bez względu na jego charakter i miejsce. Idealnie skomponowany repertuar muzyczny to nasza specjalność. Z najwyższym profesjonalizmem traktujemy zarówno eventy dla pracowników, te o charakterze kulturalnym i szkoleniowym. Kreatywność naszych artystów oraz perfekcyjnie wyselekcjonowany dla Państwa repertuar z pewnością trafi w gusta wszystkich uczestników imprezy eventowej."},

        {id:"entertainment",img: EntertainmentImg, title: "okolicznośći", heading: "Takie uroczystości wymagają najlepszej oprawy muzycznej, którą już dziś Państwu zapewnimy na najwyższym poziomie.", description: "DJ na imprezę okolicznościową, profesjonalna muzyka na żywo i oszałamiające głosy naszych wokalistów najlepiej podkreślą klimat i charakter tego wydarzenia. Gwarantujemy najlepszą zabawę, w dobrym guście i na najwyższym światowym poziomie. Przygotujemy dla Państwa idealnie skomponowany repertuar, który zachwyci gości i porwie wszystkich do wspólnej zabawy. Nasz najnowocześniejszy, profesjonalny sprzęt zapewni Państwu wyjątkowe, niezapomniane doznania muzyczne, a nasi wokaliści oraz profesjonalni muzycy zadbają o urzekający klimat Państwa imprezy."},

        {id: "photography",img: PhotographyImg,title: "fotograf", heading: "Marzycie o profesjonalnej sesji zdjęciowej, która podkreśli wyjątkowy charakter Państwa wesela?", description: "Oczekujecie Państwo niebanalnych zdjęć, które najpełniej uchwycą emocje, wzruszenie i absolutne szczęście które towarzyszy Wam w tym dniu? Dbamy o zapewnienie Państwu najlepszej sesji ślubnej, narzeczeńskiej i weselnej. Nasz fotograf ślubny gwarantuje najlepszą pamiątkę w postaci zdjęć, które nawet po latach przywołają te niezapomniane emocje i niepowtarzalny klimat wydarzenia. Każdy ślub i wesele jest inne. Dla nas to jak nowe, dotąd nieodgadnione wydarzenie, które wraz z Państwem mamy możliwość tworzyć. Stąd od początku tej przygody nasz fotograf ślubny dokumentuje ten najważniejszy dzień w Państwa życiu. Wszystko po to, aby stworzyć dla Państwa niepowtarzalną pamiątkę tego wydarzenia. Jak nikt inny potrafimy ująć subtelne, ulotne chwile i zatrzymać je na wyjątkowych, oryginalnych zdjęciach."},

        {id:"movie",img: MovieImg, title: "filmowanie", heading:"Ślub i wesele to jedno z najważniejszych wydarzeń w życiu.", decription:"Dlatego tak ważne jest profesjonalne uwiecznienie tych chwil, stworzenie unikalnej pamiątki tego dnia. Film nagrany z tej wyjątkowej uroczystości musi być na najwyższym, światowym poziomie. Proponujemy Państwu profesjonalne filmowanie wesel i innych uroczystości, a  film nagrany przez naszą ekipę to spontaniczna kronika wydarzeń. Najwyższej klasy, nowoczesny sprzęt oraz imponujące doświadczenie naszych filmowców i kamerzystów na wesele sprawia, że każdy klient otrzymuje nagranie idealnie dopasowane do jego oczekiwań i wymagań. Pomagamy Państwu utrwalić najpiękniejsze wspomnienia i chwile na długie lata. Uwielbiamy filować wesela, tworzyć z państwem historię Państwa miłości. Doskonale wiemy, że warto uchwycić miłość. Jest ona najpiękniejszym uczuciem, którym mogą darzyć się ludzie. Dbamy o każdy szczegół Państwa imprezy, uwieczniając najważniejsze momenty tak, aby po latach film nadal wzbudzał emocje i wzruszenie."},

        {id: "drink",img: DrinkImg, title: "drink-bar", heading: "Szukacie Państwo idealnego barmana na wesele? Nasza agencja barmańska to wyłącznie doświadczeni pasjonaci i wielbiciele doskonałych drinków i cocktaili.", description:"To zespół najlepszych, utalentowanych barmanów, którzy przeniosą państwa w magiczny świat najbardziej wyszukanych alkoholi. To finaliści najbardziej cenionych w branży barmańskiej konkursów, finaliście Mistrzostw Świata i Pucharu Polski. Ich drinki i coctaile zostały docenione przez najlepszych znawców sztuki barmańskiej. Proponujemy dla Pastwa profesjonalny drink bar na wesele, który zachwyci wszystkich gości. "}
    ]
}
export const ServicePageContext = createContext(services)